# https://hub.docker.com/r/linuxserver/airsonic
---
version: "2.1"
services:
  airsonic:
    image: ghcr.io/linuxserver/airsonic
    container_name: airsonic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      # - CONTEXT_PATH=<URL_BASE> #optional
      # - JAVA_OPTS=<options> #optional
    volumes:
      - /opt/airsonic/config:/config
      - ${DISK0}/music:/music
      - ${DISK0}/playlists:/playlists
      - ${DISK0}/podcasts:/podcasts
      # - ${DISK0}/othermedia:/media #optional
    ports:
      - 4040:4040
    devices:
      - /dev/snd:/dev/snd #optional
    restart: unless-stopped
