# https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Docker
version: "3"
services:
  asf:
    image: justarchi/archisteamfarm:latest
    container_name: asf
    ports:
      - 1242:1242
    volumes:
      - /opt/asf/config:/app/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
