# https://github.com/linuxserver/docker-swag
# https://docs.linuxserver.io/general/swag
---
version: "2.1"
services:
  authelia:
    image: authelia/authelia:4.21.0
    container_name: authelia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/authelia/config:/config
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
