# https://hub.docker.com/r/linuxserver/calibre-web
---
version: "2.1"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/calibreweb/config:/config
      - /mnt/disk0/books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
