# https://hub.docker.com/r/linuxserver/code-server
---
version: "2.1"
services:
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - PASSWORD=${PASS} #optional
      # - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=${PASS} #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - /opt/codeserver/config:/config
      - /opt:/opt
    ports:
      - 8443:8443
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
