# https://hub.docker.com/r/linuxserver/couchpotato
---
version: "2.1"
services:
  couchpotato:
    image: ghcr.io/linuxserver/couchpotato
    container_name: couchpotato
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/couchpotato/config:/config
      - ${DISK0}/downloads:/downloads
      - ${DISK0}/movies:/movies
    ports:
      - 5050:5050
    restart: unless-stopped
