# https://hub.docker.com/r/linuxserver/dokuwiki
---
version: "2.1"
services:
  dokuwiki:
    image: ghcr.io/linuxserver/dokuwiki
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - ${DISK0}/docker/dokuwiki/config:/config
    ports:
      - 8088:80
      - 4443:443 #optional
    restart: unless-stopped
