# https://hub.docker.com/r/linuxserver/duplicati
---
version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - CLI_ARGS= #optional
    volumes:
      - /opt/duplicati/config:/config
      - /mnt/disk0:/disk0
      - /mnt/disk1:/disk1
    ports:
      - 8200:8200
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
