# https://hub.docker.com/r/linuxserver/embystat
---
version: "2.1"
services:
  embystat:
    image: ghcr.io/linuxserver/embystat
    container_name: embystat
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/embystat/config:/config
    ports:
      - 6555:6555
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
