# https://github.com/onedr0p/exportarr
# https://github.com/onedr0p/exportarr/blob/master/examples/compose/docker-compose.yaml
version: "3.7"
services:
  sonarr-exportarr:
    image: ghcr.io/onedr0p/exportarr:latest
    command: exportarr sonarr
    container_name: sonarr-exportarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - PORT=9707
      - URL=http://sonarr:8989
      - APIKEY=${SONARR_APIKEY}
      - ENABLE_ADDITIONAL_METRICS=true
    ports:
      - 9707:9707
    restart: unless-stopped
  radarr-exportarr:
    image: ghcr.io/onedr0p/exportarr:latest
    command: exportarr radarr
    container_name: radarr-exportarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - PORT=9708
      - URL=http://radarr:7878
      - APIKEY=${RADARR_APIKEY}
      - ENABLE_ADDITIONAL_METRICS=true
    ports:
      - 9708:9708
    restart: unless-stopped
  lidarr-exportarr:
    image: ghcr.io/onedr0p/exportarr:latest
    command: exportarr lidarr
    container_name: lidarr-exportarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - PORT=9709
      - URL=http://lidarr:8686
      - APIKEY=${LIDARR_APIKEY}
    ports:
      - 9709:9709
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
