# https://github.com/linuxserver/docker-freshrss
---
version: "2.1"
services:
  freshrss:
    image: ghcr.io/linuxserver/freshrss
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/freshrss/config:/config
    restart: unless-stoppe
    labels:
      - flame.type=app # "app" works too
      - flame.name=freshrss
      - flame.url=https://freshrss.torqueserver.com/
      - flame.icon=rss
networks:
  default:
    external: true
    name: main-network
