# https://hub.docker.com/_/ghost/
version: "3.1"
services:
  ghost:
    container_name: ghost
    image: ghost:alpine
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - 'ghostdata:/var/lib/ghost/content'
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=ghost
      - flame.url=https://ghost.torqueserver.com/
      - flame.icon=ghost
networks:
  default:
    external: true
    name: main-network
volumes:
  ghostdata:
