version: "2"
services:
  web:
    image: gitea/gitea:1.12.4
    volumes:
      - /opt/gitea/data:/data
    ports:
      - "3003:3000"
      - "2222:22"
    depends_on:
      - db
    restart: always
  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=password
    volumes:
      - /opt/giteadb/db/:/var/lib/mysql
