---
version: "3"
services:
  glances:
    image: nicolargo/glances:alpine-latest
    container_name: glances
    network_mode: host
    pid: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always