---
version: "3"
services:
  glances:
    image: nicolargo/glances
    container_name: glances
    network_mode: host
    privileged: true
    pid: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - GLANCES_OPT=-w
    volumes:
      - /opt/glances/conf:/glances/conf
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 61208-61209:61208-61209
    restart: always
