# https://hub.docker.com/r/linuxserver/headphones
---
version: "2.1"
services:
  headphones:
    image: ghcr.io/linuxserver/headphones
    container_name: headphones
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/headphones/config:/config
      - ${DISK0}/downloads:/downloads
      - ${DISK0}/music:/music
    ports:
      - 8183:8181
    restart: unless-stopped
