# https://hub.docker.com/r/linuxserver/jellyfin
---
version: "2.1"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      # - JELLYFIN_PublishedServerUrl=cyan:8096 #optional
    volumes:
      - /opt/jellyfin/config:/config
      - ${DISK0}/tvseries:/data/tvshows
      - ${DISK0}/movies:/data/movies
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri #optional
    restart: unless-stopped
networks:
  default:
    external: true
    name: swag
