---
version: "2.1"
services:
  lazylibrarian:
    image: ghcr.io/linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - DOCKER_MODS=linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - /opt/lazylibrarian/config:/config
      - /mnt/disk0/downloads:/downloads
      - /mnt/disk0/books:/books
    ports:
      - 5299:5299
    restart: unless-stopped
