# https://hub.docker.com/r/linuxserver/librespeed
---
version: "2.1"
services:
  librespeed:
    image: ghcr.io/linuxserver/librespeed
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - PASSWORD=${PASS}
      - CUSTOM_RESULTS=true #optional
      - DB_TYPE=mysql #optional
      - DB_NAME=librespeed #optional
      - DB_HOSTNAME=${MARIADB} #optional
      - DB_USERNAME=librespeed #optional
      - DB_PASSWORD=${DB_PASS} #optional
      - DB_PORT=3306 #optional
    volumes:
      - /opt/librespeed/config:/config
    ports:
      - 2280:80
    restart: unless-stopped
networks:
  default:
    external: true
    name: mariadb
