version: "3"
services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    user: "1000:1001"
    ports:
      - "8081:8081"
    volumes:
      - /mnt/disk0/downloads:/downloads
