# https://github.com/alexta69/metube
version: "3"
services:
  metube:
    image: alexta69/metube
    container_name: metube
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - ${DISK0}/downloads:/downloads
    ports:
      - 8081:8081
    restart: unless-stopped
