# https://github.com/ccrisan/motioneye/wiki/Install-In-Docker
---
version: "3"
services:
  motioneye:
    image: ccrisan/motioneye:master-amd64
    container_name: motioneye
    volumes:
      - /opt/motioneye/etc:/etc
      - /opt/motioneye/var/lib/motioneye:/var/lib/motioneye
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8765:8765
    restart: always
networks:
  default:
    external: true
    name: main
