# https://hub.docker.com/r/linuxserver/muximux
---
version: "2.1"
services:
  muximux:
    image: ghcr.io/linuxserver/muximux
    container_name: muximux
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/muximux/config:/config
    ports:
      - 8189:80
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
