# https://hub.docker.com/r/linuxserver/nextcloud
---
version: "2.1"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - ${DISK0}/docker/nextcloud/config:/config
      - ${DISK0}/nextcloud:/data
    ports:
      - 4443:443
    restart: unless-stopped
networks:
  default:
    external: true
    name: mariadb
