---
version: "2.1"
services:
  nginx:
    image: ghcr.io/linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - ${DISK0}/nginx/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
