# https://hub.docker.com/r/linuxserver/ngircd
---
version: "2.1"
services:
  ngircd:
    image: ghcr.io/linuxserver/ngircd
    container_name: ngircd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/ngircd/config:/config
      - /opt/ngircd/ssh:/etc/ngircd/ssl
    ports:
      - 6667:6667
      - 6697:6697
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
