---
version: "2.1"
services:
  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/nzbget/config:/config
      - /mnt/disk0/downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
