# https://hub.docker.com/r/linuxserver/nzbget
---
version: "2.1"
services:
  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - ${DISK0}/docker/nzbget/config:/config
      - ${DISK0}/downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
networks:
  default:
    external: true
    name: servarr
