# https://hub.docker.com/r/linuxserver/ombi
---
version: "2.1"
services:
  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      # - BASE_URL=/ombi #optional
    volumes:
      - /opt/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
networks:
  default:
    external: true
    name: servarr
