# https://docs.organizr.app/books/installation/page/docker
version: "3.6"
services:
  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr:latest
    ports:
      - 8089:80
    volumes:
      - /opt/organizr/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
