---
version: "2.1"
services:
  overseerr:
    image: ghcr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
networks:
  default:
    external: true
    name: servarr
