---
version: "2.1"
services:
  photoshow:
    image: ghcr.io/linuxserver/photoshow
    container_name: photoshow
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/photoshow/config:/config
      - /mnt/disk0/pictures/photoshow:/Pictures:ro
      - /mnt/disk0/pictures/photoshow/thumbs:/Thumbs
    ports:
      - 2341:80
    restart: unless-stopped
