# https://github.com/eko/pihole-exporter
version: "3"
services:
  pi-hole-exporter:
    image: ekofr/pihole-exporter:latest
    container_name: pihole-exporter
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - PIHOLE_HOSTNAME=${CYAN}
      - PIHOLE_PORT=8088
      - PIHOLE_API_TOKEN="${PIHOLE_API}"
      - INTERVAL=30s
      - PORT=9617
    # logging:
    # driver: "json-file"
    # options:
    # max-size: 10m
    # max-file: "3"
    # labels: "pihole-exporter"
    ports:
      - "9617:9617"
    networks:
      default:
        ipv4_address: ${PIHOLE_EXPORTER_IP}
    restart: unless-stopped
networks:
  default:
    external: true
    name: grafana
