# https://github.com/eko/pihole-exporter
version: "3"
services:
  pi-hole-exporter:
    image: ekofr/pihole-exporter:latest
    container_name: pihole_exporter
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - PIHOLE_HOSTNAME=${CYAN}
      - PIHOLE_PASSWORD=${PIHOLE_PASS}
      - PORT=9617
    ports:
      - "9617:9617"
    restart: unless-stopped
networks:
  default:
    external: true
    name: grafana
