#https://github.com/pi-hole/docker-pi-hole
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8087:80/tcp"
    environment:
      TZ: "Asia/Kuala_Lumpur"
      WEBPASSWORD: ${PASS}
    # Volumes store your data between container upgrades
    volumes:
      - "/opt/pihole/etc/pihole/:/etc/pihole/"
      - "/opt/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/"
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
networks:
  default:
    external: true
    name: main-network
