# https://hub.docker.com/r/linuxserver/piwigo
---
version: "2.1"
services:
  piwigo:
    image: ghcr.io/linuxserver/piwigo
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/piwigo/config:/config
      - ${DISK0}/piwigo/gallery:/gallery
    ports:
      - 8778:80
    restart: unless-stopped
networks:
  default:
    external: true
    name: mariadb
