# https://hub.docker.com/r/linuxserver/plex
---
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      # - PLEX_CLAIM= ${PLEX_CLAIM}
    volumes:
      - ${DISK0}/docker/plex/config:/config
      - ${DISK0}/tvseries:/tv
      - ${DISK0}/movies:/movies
      - /dev/dri:/dev/dri
    restart: unless-stopped
