---
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /opt/plex/config:/config
      - /mnt/disk0/tvseries:/tv
      - /mnt/disk0/movies:/movies
      - /dev/dri:/dev/dri
    restart: unless-stopped
