# https://hub.docker.com/_/postfixadmin
---
version: "3"

services:
  postfixadmin:
    container_name: postfixadmin
    image: postfixadmin
    ports:
      - 8002:80
    restart: always
    environment:
      POSTFIXADMIN_DB_TYPE: mysqli
      POSTFIXADMIN_DB_HOST: mariadb
      POSTFIXADMIN_DB_USER: postfixadmin
      POSTFIXADMIN_DB_NAME: postfixadmin
      POSTFIXADMIN_DB_PASSWORD: password
    volumes:
      - /opt/postfixadmin/html:/var/www/html
networks:
  default:
    external: true
    name: main
