---
version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data/
      # - /opt/postgres/postgres.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    restart: unless-stopped
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - PGADMIN_DEFAULT_EMAIL=torq@duck.com
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '8008:80'
    labels:
      - flame.type=app # "app" works too
      - flame.name=pgadmin4
      - flame.url=http://192.168.0.105:8008/
      - flame.icon=database
    restart: unless-stopped
networks:
  default:
    external: true
    name: main-network
volumes:
  pgdata:
    external: true
