# https://hub.docker.com/r/privatebin/nginx-fpm-alpine
---
version: '3'
services:
  nginx-fpm-alpine:
    container_name: privatebin
    image: privatebin/nginx-fpm-alpine
    volumes:
      - 'privatebin-data:/srv/data'
    ports:
      - '8580:8080'
    restart: unless-stopped
    read_only: true
networks:
  default:
    external: true
    name: main-network
volumes:
  privatebin-data: