# https://prometheus.io/docs/prometheus/latest/installation/
version: "3"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    ports:
      - 9090:9090
    volumes:
      - /opt/prometheus:/etc/prometheus
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
