# https://hub.docker.com/r/linuxserver/pyload
---
version: "2.1"
services:
  pyload:
    image: ghcr.io/linuxserver/pyload
    container_name: pyload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - ${DISK0}/docker/pyload/config:/config
      - ${DISK0}/downloads:/downloads
    ports:
      - 8008:8000
      # - 7227:7227 #optional
    restart: unless-stopped
