# https://hub.docker.com/r/linuxserver/pyload-ng
---
version: "2.1"
services:
  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng
    container_name: pyload-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/pyload-ng/config:/config
      - /mnt/disk0/downloads:/downloads
    ports:
      - 8100:8000
      - 9666:9666 #optional
    restart: unless-stopped
networks:
  default:
    external: true
    name: main-network