# https://hub.docker.com/r/linuxserver/radarr
---
version: "2.1"
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/radarr/config:/config
      - ${DISK0}/movies:/movies
      - ${DISK0}/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
