# https://hub.docker.com/r/linuxserver/raneto
---
version: "2.1"
services:
  raneto:
    image: ghcr.io/linuxserver/raneto
    container_name: raneto
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/raneto/config:/config
    ports:
      - 3000:3000
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
