# https://hub.docker.com/r/linuxserver/readarr
---
version: "2.1"
services:
  readarr:
    image: ghcr.io/linuxserver/readarr:nightly
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/readarr/config:/config
      - ${DISK0}/books:/books #optional
      - ${DISK0}/downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped
networks:
  default:
    external: true
    name: servarr
