---
version: "3.2"
services:
  redis:
    image: "redis:alpine"
    command: redis-server
    container_name: redis
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/redis/data:/data
      - /opt/redis/etc/redis:/usr/local/etc/redis
    ports:
      - 6379:6379
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
