# https://docs.redis.com/latest/ri/installing/install-docker/
# https://hub.docker.com/_/redis/
---
version: "3.2"
services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: redis
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - redisdata:/data
      # - /opt/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    restart: unless-stopped
  redisinsight:
    image: "redislabs/redisinsight:latest"
    container_name: redisinsight
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - redisinsight:/db
    ports:
      - 8001:8001
    depends_on:
      - "redis"
    labels:
      - flame.type=app # "app" works too
      - flame.name=redisinsight
      - flame.url=http://192.168.0.105:8001/
      - flame.icon=database
networks:
  default:
    external: true
    name: main-network
volumes:
  redisdata:
  redisinsight: