---
version: "2.1"
services:
  requestrr:
    image: ghcr.io/linuxserver/requestrr
    container_name: requestrr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/requestrr/config:/config
    ports:
      - 4545:4545
    restart: unless-stopped
