# https://hub.docker.com/r/linuxserver/sabnzbd
---
version: "2.1"
services:
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/sabnzbd/config:/config
      - ${DISK0}/downloads:/downloads #optional
      - ${DISK0}/downloads/incomplete:/incomplete-downloads #optional
    ports:
      - 8081:8080
      - 9090:9090
    restart: unless-stopped
networks:
  default:
    external: true
    name: servarr
