# https://hub.docker.com/r/linuxserver/sonarr
---
version: "2.1"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/sonarr/config:/config
      - ${DISK0}/tvseries:/tv
      - ${DISK0}/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
