# https://github.com/linuxserver/docker-swag
# https://docs.linuxserver.io/general/swag
---
version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - URL=4mirul.com
      - SUBDOMAINS=h,q,wiki,plex,jellyfin,overseerr
      - VALIDATION=http
      # - CERTPROVIDER= #optional
      # - DNSPLUGIN=cloudflare #optional
      # - PROPAGATION= #optional
      # - DUCKDNSTOKEN= #optional
      - EMAIL=${EMAIL} #optional
      - ONLY_SUBDOMAINS=true #optional
      # - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
      # - MAXMINDDB_LICENSE_KEY= #optional
    volumes:
      - /opt/swag/config:/config
      - /opt/jellyfin/config/log:/jellyfin/log
      - /opt/overseerr/config/logs:/overseerr/logs
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
  authelia:
    image: authelia/authelia:4.21.0
    container_name: authelia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/authelia/config:/config
    restart: unless-stopped
networks:
  default:
    external: true
    name: swag
