# https://github.com/linuxserver/docker-swag
# https://docs.linuxserver.io/general/swag
---
version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - URL=torqueserver.com
      - SUBDOMAINS=www,h,plex,jellyfin,overseerr,heimdall,netdata
      - VALIDATION=http
      # - CERTPROVIDER= #optional
      # - DNSPLUGIN=cloudflare #optional
      # - PROPAGATION= #optional
      # - DUCKDNSTOKEN= #optional
      - EMAIL=torq@duck.com #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS=h.4mirul.com, overseerr.4mirul.com, jellyfin.4mirul.com, plex.4mirul.com, heimdall.4mirul.com, netdata.4mirul.com #optional
      - STAGING=false #optional
      # - MAXMINDDB_LICENSE_KEY= #optional
    volumes:
      - /opt/swag/config:/config
      - /opt/jellyfin/config/log:/jellyfin/log
      - /opt/overseerr/config/logs:/overseerr/logs
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
  authelia:
    image: authelia/authelia:master
    container_name: authelia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/authelia/config:/config
    ports:
      - 9091:9091
    restart: unless-stopped
networks:
  default:
    external: true
    name: main-network
