# https://hub.docker.com/_/teamspeak/
---
version: "3.1"
services:
  teamspeak:
    image: teamspeak
    container_name: teamspeak
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Kuala_Lumpur
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: mariadb
      TS3SERVER_DB_USER: teamspeak
      TS3SERVER_DB_PASSWORD: ${PASS}
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
networks:
  default:
    external: true
    name: main
