---
version: "2.1"
services:
  ubooquity:
    image: ghcr.io/linuxserver/ubooquity
    container_name: ubooquity
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - MAXMEM=1024
    volumes:
      - /opt/ubooquity/config:/config
      - /mnt/disk0/books:/books
      - /mnt/disk0/comics:/comics
      - /mnt/disk0/files:/files
    ports:
      - 2202:2202
      - 2203:2203
    restart: unless-stopped
