# https://registry.hub.docker.com/r/fauria/vsftpd/
---
version: "2.1"
services:
  vsftpd:
    image: fauria/vsftpd
    container_name: vsftpd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - FTP_USER=admin
      - FTP_PASS=password
    volumes:
      - /mnt/disk0/downloads:/downloads
    ports:
      - 21:21
      - 20:20
      - 21100-21110:21100-21110
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
