# https://hub.docker.com/r/linuxserver/webtop
---
version: "2.1"
services:
  webtop:
    image: ghcr.io/linuxserver/webtop:alpine-i3
    container_name: webtop
    privileged: true #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      # - SUBFOLDER=/ #optional
    volumes:
      - /opt/webtop/config:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3003:3000
    shm_size: "1gb" #optional
    restart: unless-stopped
