# https://hub.docker.com/r/linuxserver/wikijs
---
version: "2.1"
services:
  wikijs:
    image: ghcr.io/linuxserver/wikijs
    container_name: wikijs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - DB_TYPE=mariadb
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=wikijs
      - DB_PASS=${DB_PASS}
      - DB_NAME=wikijs
    volumes:
      - /opt/wikijs/config:/config
      - /opt/wikijs/data:/data
    ports:
      - 3006:3000
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
