# https://hub.docker.com/r/linuxserver/wikijs
---
version: "2.1"
services:
  wikijs:
    image: ghcr.io/linuxserver/wikijs
    container_name: wikijs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - ${DISK0}/docker/wikijs/config:/config
      - ${DISK0}/docker/wikijs/data:/data
    ports:
      - 3006:3000
    restart: unless-stopped
