# https://hub.docker.com/_/wordpress/
version: "3.1"
services:
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 8187:80
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Kuala_Lumpur
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
networks:
  default:
    external: true
    name: main-network
volumes:
  wordpress:
