# https://hub.docker.com/_/adminer/
---
version: "3"
services:
  adminer:
    container_name: adminer
    image: adminer:latest
    environment:
      - TZ=Asia/Kuala_Lumpur
      - ADMINER_DEFAULT_SERVER=mariadb
    ports:
      - 8180:8080
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=adminer
      - flame.url=http://${HOSTNAME}:8180/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=database # https://materialdesignicons.com/
networks:
  default:
    external: true
    name: main-network
