# https://hub.docker.com/_/adminer/
---
version: "3"
services:
  adminer:
    container_name: adminer
    image: adminer:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    ports:
      - 8970:8080
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=adminer
      - flame.url=http://${HOSTNAME}:8970/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=database # https://materialdesignicons.com/
      - homepage.group=Databases # homepage label https://github.com/benphelps/homepage
      - homepage.name=adminer
      - homepage.icon=adminer.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:8970/
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
