# https://hub.docker.com/r/linuxserver/airsonic-advanced
---
version: "2.1"
services:
  airsonic-advanced:
    image: lscr.io/linuxserver/airsonic-advanced
    container_name: airsonic-advanced
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      # - CONTEXT_PATH=<URL_BASE> #optional
      # - JAVA_OPTS=<options> #optional
    volumes:
      - /opt/airsonic-advanced/config:/config
      - /mnt/disk0/music:/music
      - /mnt/disk0/playlists:/playlists
      - /mnt/disk0/podcasts:/podcasts
    ports:
      - 4040:4040
    devices:
      - /dev/snd:/dev/snd #optional
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=airsonic
      - flame.url=https://airsonic.torqueserver.com/
      - flame.icon=music
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main_network
