services:
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - "/opt/alertmanager/alertmanager.yml:/alertmanager/alertmanager.yml"
    ports:
      - 9093:9093
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=alertmanager
      - flame.url=http://${HOSTNAME}:9093/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=alarm # https://materialdesignicons.com/
networks:
  default:
    external: true
    name: main-network