# https://github.com/answerdev/answer
---
version: "3"
services:
  answer:
    image: answerdev/answer
    container_name: answer
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    ports:
      - "9080:80"
    restart: unless-stopped
    volumes:
      - answer-data:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=answer
      - flame.url=https://answer.${DOMAIN}/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=chat-question # https://materialdesignicons.com/
      - homepage.group=Q&A Platform # homepage label https://github.com/benphelps/homepage
      - homepage.name=answer
      - homepage.icon=mdi-chat-question # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=https://answer.${DOMAIN}/
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
volumes:
  answer-data:
    external: true
