# https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Docker
---
version: "3"
services:
  asf:
    image: justarchi/archisteamfarm:latest
    container_name: asf
    ports:
      - 1242:1242
    volumes:
      - /opt/asf/config:/app/config
    environment:
      - TZ=Asia/Kuala_Lumpur
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=asf
      - flame.url=http://${HOSTNAME}:1242/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=steam # https://materialdesignicons.com/
      # - homepage.group=Games # homepage label https://github.com/benphelps/homepage
      # - homepage.name=asf
      # - homepage.icon=archisteamfarm.png # https://gethomepage.dev/en/configs/services/#icons
      # - homepage.href=http://${HOSTNAME}:1242/
      # - homepage.description=
networks:
  default:
    external: true
    name: main-network
