# https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Docker
version: "3"
services:
  asf:
    image: justarchi/archisteamfarm:latest
    container_name: asf
    ports:
      - 1242:1242
    volumes:
      - /opt/asf/config:/app/config
    environment:
      - TZ=Asia/Kuala_Lumpur
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=asf
      - flame.url=http://torqueserver.home:1242
      - flame.icon=steam
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main-network
