# https://github.com/linuxserver/docker-swag
# https://docs.linuxserver.io/general/swag
---
version: "3.8"
services:
  authelia:
    container_name: authelia
    image: docker.io/authelia/authelia:latest
    restart: unless-stopped
    networks:
      default:
        aliases: []
    expose:
      - 9091
    environment:
      AUTHELIA_JWT_SECRET_FILE: /secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /secrets/SESSION_SECRET
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /secrets/STORAGE_PASSWORD
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/STORAGE_ENCRYPTION_KEY
    volumes:
      - /opt/authelia/config:/config
      - /opt/authelia/secrets:/secrets
    labels:
      - flame.type=app # "app" works too
      - flame.name=authelia
      - flame.url=https://authelia.torqueserver.com/
      - flame.icon=lock
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main-network
