# https://hub.docker.com/r/linuxserver/bazarr
---
version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/bazarr/config:/config
      - ${DISK0}/movies:/movies
      - ${DISK0}/tvseries:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=bazarr
      - flame.url=http://${HOSTNAME}:6767/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=subtitles # https://materialdesignicons.com/
      # - homepage.group=Download Managers # homepage label https://github.com/benphelps/homepage
      # - homepage.name=bazarr
      # - homepage.icon=bazarr.png # https://gethomepage.dev/en/configs/services/#icons
      # - homepage.href=http://${HOSTNAME}:6767/
      # - homepage.description=
networks:
  default:
    external: true
    name: main-network
