# https://hub.docker.com/r/linuxserver/bazarr
---
version: "2.1"
services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/bazarr/config:/config
      - /mnt/disk1/movies:/movies
      - /mnt/disk0/tvseries:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    labels:
      # - flame.type=app # "app" works too
      # - flame.name=bazarr
      # - flame.url=http://192.168.0.126:6767/
      # - flame.icon=subtitles
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main_network
