# https://github.com/prometheus/blackbox_exporter
---
version: "3"
services:
  blackbox-exporter:
    image: prom/blackbox-exporter:master
    container_name: blackbox-exporter
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    ports:
      - 9115:9115
    volumes:
      - /opt/blackbox-exporter:/config
    restart: unless-stopped
networks:
  default:
    external: true
    name: main-network
