version: '3'
services:
  budgetzero:
    container_name: budgetzero
    image: budgetzero/budgetzero
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    ports:
      - '8085:8080'
    labels:
      - flame.type=app # "app" works too
      - flame.name=budgetzero
      - flame.url=http://192.168.0.105:8085/
      - flame.icon=currency-usd
    restart: unless-stopped
networks:
  default:
    external: true
    name: main-network