# https://hub.docker.com/r/budgetzero/budgetzero
---
version: "3"
services:
  budgetzero:
    container_name: budgetzero
    image: budgetzero/budgetzero
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    ports:
      - "8085:8080"
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=budgetzero
      - flame.url=http://${HOSTNAME}:8085/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=currency-usd # https://materialdesignicons.com/
      - homepage.group=Personal Finance # homepage label https://github.com/benphelps/homepage
      - homepage.name=Budgetzero
      - homepage.icon=icon_name.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:8085/
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
