# https://github.com/linuxserver/docker-budge/
---
version: "2.1"
services:
  budge:
    image: lscr.io/linuxserver/budge
    container_name: budge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/budge/config:/config
    ports:
      - 8810:80
      - 5443:443
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=budge
      - flame.url=http://${HOSTNAME}:8810/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=currency-usd # https://materialdesignicons.com/
      - homepage.group=Personal Finance # homepage label https://github.com/benphelps/homepage
      - homepage.name=Budge
      - homepage.icon=mdi-currency-usd # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:8810/
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
