# https://hub.docker.com/r/clearlinux/cgit
---
version: "3"
services:
  cgit:
    image: clearlinux/cgit
    container_name: cgit
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    ports:
      - "9380:80"
    restart: unless-stopped
    volumes:
      - /home/yuu/work:/var/www/cgit
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=cgit
      - flame.url=http://${HOSTNAME}:9380/cgit # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=git # https://materialdesignicons.com/
      - homepage.group=Version Control # homepage label https://github.com/benphelps/homepage
      - homepage.name=cgit
      - homepage.icon=git.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:9380/cgit
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
