# https://hub.docker.com/r/clearlinux/cgit
---
version: "3"
services:
  cgit:
    image: clearlinux/cgit
    container_name: cgit
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    ports:
      - "9380:80"
    restart: unless-stopped
    volumes:
      - /home/yuu/work:/var/www/cgit
    labels:
      - flame.type=app # "app" works too
      - flame.name=cgit
      - flame.url=http://torqueserver.home:9380/cgit/
      - flame.icon=git
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main-network
