# https://hub.docker.com/r/linuxserver/ddclient
---
version: "2.1"
services:
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/ddclient/config:/config
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
networks:
  default:
    external: true
    name: main-network
