# https://hub.docker.com/r/discordirc/discord-irc
---
version: "3"
services:
  discordirc:
    container_name: discordirc
    image: discordirc/discord-irc
    volumes:
      - /opt/discordirc/config/config.json:/config/config.json
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
networks:
  default:
    external: true
    name: main-network