# 
---
services:
  diskover:
    image: lscr.io/linuxserver/diskover
    container_name: diskover
    environment:
      - TZ=Asia/Kuala_Lumpur
      - ES_HOST=172.18.0.1
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASS=changeme
    volumes:
      - /opt/diskover/config:/config
      - /opt/diskover/data:/data
    ports:
      - 8490:80
    mem_limit: 4096m
    restart: unless-stopped
    depends_on:
      - elasticsearch
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=diskover
      - flame.url=http://${HOSTNAME}:8490/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=ssd # https://pictogrammers.com/library/mdi/
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
      # - /opt/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    depends_on:
      - elasticsearch-helper
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
  elasticsearch-helper:
    container_name: elasticsearch-helper
    image: alpine
    command: sh -c "sysctl -w vm.max_map_count=262144"
    privileged: true
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
networks:
  default:
    external: true
    name: main-network