# https://github.com/docker-mailserver/docker-mailserver
---
version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: torqueserver
    domainname: torqueserver.com
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - /opt/mailserver/docker-data/dms/mail-data/:/var/mail/
      - /opt/mailserver/docker-data/dms/mail-state/:/var/mail-state/
      - /opt/mailserver/docker-data/dms/mail-logs/:/var/log/mail/
      - /opt/mailserver/docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_SASLAUTHD=0
      - ONE_DIR=1
    cap_add:
      - NET_ADMIN
    restart: always
