# https://hub.docker.com/r/linuxserver/dokuwiki
---
version: "2.1"
services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/dokuwiki/config:/config
    ports:
      - 8688:80
      - 4443:443 #optional
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=dokuwiki
      - flame.url=http://torqueserver.home:8688/
      - flame.icon=book-open
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main_network