# https://hub.docker.com/r/linuxserver/duplicati
---
version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - CLI_ARGS= #optional
    volumes:
      - /opt/duplicati/config:/config
      - ${DISK0}:/disk0
      - ${DISK1}:/disk1
    ports:
      - 8200:8200
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=duplicati
      - flame.url=http://${HOSTNAME}:8200/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=cloud-upload # https://materialdesignicons.com/
      - homepage.group=File Management/Synchronization # homepage label https://github.com/benphelps/homepage
      - homepage.name=duplicati
      - homepage.icon=duplicati.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:8200/
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
