# https://hub.docker.com/r/linuxserver/duplicati
---
version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - CLI_ARGS= #optional
    volumes:
      - /opt/duplicati/config:/config
      - /mnt/disk0:/disk0
      - /mnt/disk1:/disk1
    ports:
      - 8200:8200
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=duplicati
      - flame.url=torqueserver.home:8200/
      - flame.icon=content-duplicate
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main_network
