# https://hub.docker.com/r/linuxserver/emby
# https://hub.docker.com/r/emby/embyserver/#!
---
version: "2.3"
services:
  emby:
    image: emby/embyserver:latest
    container_name: embyserver
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/emby/config:/config
      - /home/yuu/media/tv:/data/tvshows
      - /home/yuu/media/movies:/data/movies
      # - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8097:8096
      - 8920:8920
    devices:
      - /dev/dri:/dev/dri
    # runtime: nvidia
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=emby
      - flame.url=https://emby.torqueserver.com/
      # - flame.url=http://192.168.0.126:8096
      - flame.icon=emby
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main_network
