# https://hub.docker.com/r/linuxserver/emby
# https://hub.docker.com/r/emby/embyserver/#!
---
version: "2.3"
services:
  emby:
    image: emby/embyserver
    container_name: embyserver
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/emby/config:/config
      - /mnt/disk0/tvseries:/data/tvshows
      - /mnt/disk1/movies:/data/movies
      # - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8097:8096
      # - 8920:8920
    devices:
      - /dev/dri:/dev/dri
    # runtime: nvidia
    restart: unless-stopped
networks:
  default:
    external: true
    name: main-network
