# https://filebrowser.org/installation/
---
version: "3"
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    environment:
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /:/srv
    ports:
      - 7880:80
    restart: unless-stopped
networks:
  default:
    external: true
    name: main-network
