# https://filebrowser.org/installation/
---
version: "3"
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /:/srv
      - /opt/filebrowser/database.db:/database.db # If you don't already have a database file, make sure to create a new empty file under the path you specified. Otherwise, Docker will create an empty folder instead of an empty file, resulting in an error when mounting the database into the container.
      - /opt/filebrowser/.filebrowser.json:/.filebrowser.json
    ports:
      - 7880:80
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=filebrowser
      - flame.url=http://${HOSTNAME}:7880/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=folder # https://materialdesignicons.com/
      - homepage.group=File Management/Synchronization # homepage label https://github.com/benphelps/homepage
      - homepage.name=filebrowser
      - homepage.icon=filebrowser.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:7880/
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
