# https://github.com/ShaneIsrael/fireshare
---
version: "3"
services:
  fireshare:
    container_name: fireshare
    image: "shaneisrael/fireshare:latest"
    environment:
      - ADMIN_PASSWORD=${PASS}
    volumes:
      - "${DISK1}/fireshare/data:/data:rw"
      - "${DISK1}/fireshare/processed:/processed:rw"
      - "${DISK1}/fireshare/clips:/videos:rw"
    ports:
      - "8085:80"
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=fireshare
      - flame.url=http://${HOSTNAME}:8085/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=cloud-upload # https://materialdesignicons.com/
      - homepage.group=Media # homepage label https://github.com/benphelps/homepage
      - homepage.name=fireshare
      - homepage.icon=mdi-cloud-upload # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:8085/
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
