# https://github.com/pawelmalak/flame
# https://github.com/squidfunk/mkdocs-material
# https://www.tecmint.com/shellinabox-web-based-ssh-linux-terminal/
---
services:
  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    volumes:
      - flame-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    ports:
      - 5005:5005
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - PASSWORD=${PASS}
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=flame dashboard;proxmox;shell in a box;cockpit;docs;netdata #;torqueserver documents;shell in a box;torqueserver;proxmox;dir
      - flame.url=http://${HOSTNAME}:5005/;https://proxmox.${DOMAIN}/;https://sh.${DOMAIN};https://cockpit.${DOMAIN};https://docs.${DOMAIN};http://${HOSTNAME}:19999/ #;https://docs.${DOMAIN}/;https://sh.${DOMAIN}/;https://${DOMAIN}/;https://proxmox.${DOMAIN}/;https://dir.${DOMAIN}/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=fire-circle;server-network;ssh;console;file-document-multiple-outline;chart-bar #;file-document-multiple-outline;ssh;server-network;file-tree # https://materialdesignicons.com/

networks:
  default:
    external: true
    name: main-network
volumes:
  flame-data:
    external: true
