# https://docs.gitea.io/en-us/install-with-docker/
version: "3"
services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mariadb:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${PASS}
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - "2222:22"
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=gitea
      - flame.url=https://gitea.torqueserver.com/
      - flame.icon=git
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main-network
volumes:
  gitea:
    external: true
