# https://glances.readthedocs.io/en/latest/docker.html
---
services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    network_mode: host
    hostname: glances
    pid: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=glances
      - flame.url=https://glances.${DOMAIN}/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=eye # https://materialdesignicons.com/
