# https://glances.readthedocs.io/en/latest/docker.html
---
version: "3"
services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    network_mode: host
    hostname: glances
    pid: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=glances
      - flame.url=http://${HOSTNAME}:61208/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=eye # https://materialdesignicons.com/
      - homepage.group=Monitoring and Analytics # homepage label https://github.com/benphelps/homepage
      - homepage.name=glances
      - homepage.icon=glances.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:61208/
      - homepage.description=
