---
version: "3"
services:
  glances:
    image: nicolargo/glances:alpine-latest
    container_name: glances
    network_mode: host
    pid: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - GLANCES_OPT=-w
    labels:
      - flame.type=app # "app" works too
      - flame.name=glances
      - flame.url=http://192.168.0.126:61208/
      - flame.icon=eye
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always