# https://hub.docker.com/r/elestio/glpi
---
services:
  glpi:
    image: elestio/glpi:latest
    container_name: glpi
    environment:
      - TZ=Asia/Kuala_Lumpur
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=glpi
      - flame.url=https://glpi.${DOMAIN}/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=ticket # https://materialdesignicons.com/
networks:
  default:
    external: true
    name: main-network
