# https://hub.docker.com/r/linuxserver/heimdall
---
version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/heimdall/config:/config
    ports:
      - 8888:80
      - 3443:443
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=heimdall
      - flame.url=http://${HOSTNAME}:8888/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=crown # https://materialdesignicons.com/
      - homepage.group=Personal Homepage # homepage label https://github.com/benphelps/homepage
      - homepage.name=heimdall
      - homepage.icon=heimdall.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:8888/
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
