# https://github.com/bastienwirtz/homer
---
version: '3'
services:
  homer:
    container_name: homer
    image: 'b4bz/homer:latest'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - '/opt/homer/www/assets:/www/assets'
    ports:
      - '8680:8080'
    restart: unless-stopped
networks:
  default:
    external: true
    name: main-network