# https://github.com/benphelps/homepage
---
services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    environment:
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DISK0}:/disk0:ro
      - ${DISK1}:/disk1:ro
    ports:
      - 3900:3000
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - flame.type=app # "app" works too
      - flame.name=homepage
      - flame.url=https://homepage.${DOMAIN}/
      - flame.icon=home
      - homepage.group=Dashboard # homepage label https://gethomepage.dev/
      - homepage.name=Homepage
      - homepage.icon=homepage.png # https://pictogrammers.com/library/mdi/ or https://github.com/walkxcode/dashboard-icons/tree/main/png
      - homepage.href=https://homepage.${DOMAIN}/
      - homepage.instance.internal.href=http://${HOSTNAME}:3900/
      - homepage.instance.public.href=https://homepage.${DOMAIN}/
      - homepage.description=
      # - homepage.widget.type=homepage
      # - homepage.widget.url=http://${HOST}:3900/
      # - homepage.widget.key=yourembyapikeyhere
      # - homepage.widget.fields=["field1","field2"] # optional
networks:
  default:
    external: true
    name: main-network
