# https://hub.docker.com/_/influxdb/
version: "3.3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb2data:/var/lib/influxdb2
      - influxdb2config:/etc/influxdb2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=influxdb
      - flame.url=http://192.168.0.105:8086/
      - flame.icon=chart-line
networks:
  default:
    external: true
    name: main-network
volumes:
  influxdb2data:
  influxdb2config:
