# https://hub.docker.com/r/linuxserver/jackett
---
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - AUTO_UPDATE=true #optional
    volumes:
      - /opt/jackett/config:/config
      - /mnt/disk0/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=jackett
      - flame.url=http://torqueserver.home:9117/
      - flame.icon=tshirt-crew
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main-network
