# https://jellyfin.org/docs/
# https://jellyfin.org/docs/general/administration/hardware-acceleration/
---
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    network_mode: "host"
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - ${DISK0}/tvseries:/data/tvseries
      - ${DISK0}/movies:/data/movies
      - /dev/dri:/dev/dri
    restart: "unless-stopped"
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.${DOMAIN}/
    devices:
      - /dev/dri:/dev/dri
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - flame.type=app # "app" works too
      - flame.name=jellyfin
      - flame.url=https://jellyfin.${DOMAIN}/
      - flame.icon=jellyfish
volumes:
  jellyfin-config:
    external: true
  jellyfin-cache:
    external: true
