# https://github.com/Fallenbagel/jellyseerr
---
version: "3"
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Kuala_Lumpur
    ports:
      - 5051:5055
    volumes:
      - /opt/jellyseerr/config:/app/config
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=jellyseerr
      - flame.url=http://${HOSTNAME}:5051/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=jellyfish-outline # https://materialdesignicons.com/
      - homepage.group=Media Request and Management # homepage label https://github.com/benphelps/homepage
      - homepage.name=jellyseerr
      - homepage.icon=jellyseerr.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:5051/
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
