# https://github.com/jenkinsci/docker
---
version: "3"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - 8180:8080
    volumes:
      - jenkins-home:/var/jenkins_home
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=jenkins
      - flame.url=http://${HOSTNAME}:8180/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=account-tie # https://materialdesignicons.com/
      - homepage.group=CI/CD tools # homepage label https://github.com/benphelps/homepage
      - homepage.name=jenkins
      - homepage.icon=jenkins.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:8180/
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
volumes:
  jenkins-home:
    external: true
