# https://example.com/
---
version: "3"
services:
  jfa-go:
    container_name: jfa-go
    image: "hrfee/jfa-go"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/jfa-go:/data
      - jellyfin-config:/jf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8056:8056"
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=jfa-go
      - flame.url=https://jfa.torqueserver.com/
      - flame.icon=jellyfish
networks:
  default:
    external: true
    name: main-network
volumes:
  jellyfin-config:
    external: true
