# https://jfa-go.com/
---
version: "3"
services:
  jfa-go:
    container_name: jfa-go
    image: "hrfee/jfa-go"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/jfa-go:/data
      - jellyfin-config:/jf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8056:8056"
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=jfa-go
      - flame.url=https://jfa.${DOMAIN}/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=jellyfish # https://materialdesignicons.com/
      - homepage.group=Media Request and Management # homepage label https://github.com/benphelps/homepage
      - homepage.name=jfa-go
      - homepage.icon=jellyfin.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=https://jfa.${DOMAIN}/
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
volumes:
  jellyfin-config:
    external: true
