# https://hub.docker.com/r/linuxserver/lidarr
---
version: "2.1"
services:
  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/lidarr/config:/config
      - ${DISK0}/music:/music
      - ${DISK0}/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
