# https://hub.docker.com/r/linuxserver/lidarr
---
version: "2.1"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/lidarr/config:/config
      - /mnt/disk0/music:/music
      - /mnt/disk0/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=lidarr
      - flame.url=http://torqueserver.home:8686/
      - flame.icon=music
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main_network
