# https://github.com/joseantmazonsb/linguard
---
version: "3.6"

services:
  linguard:
    image: "ghcr.io/joseantmazonsb/linguard:stable"
    container_name: "linguard"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/linguard/data:/data" # Optional, provides a way to see and edit the configuration files directly from the host.
    network_mode: host
    restart: unless-stopped
    # ports:
    #   - "8580:8080"
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=linguard
      - flame.url=http://${HOSTNAME}:8080/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=vpn # https://materialdesignicons.com/
      - homepage.group=Tools # homepage label https://github.com/benphelps/homepage
      - homepage.name=linguard
      - homepage.icon=linguard.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:8080/
      - homepage.description=
