# https://hub.docker.com/r/gliderlabs/logspout/
---
services:
  logspout:
    container_name: logspout
    image: gliderlabs/logspout:latest
    environment:
      - ALLOW_TTY=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
    #   - flame.type=app # flame label https://github.com/pawelmalak/flame
    #   - flame.name=logspout
    #   - flame.url=http://${LOGSPOUT_IP}:80/logs # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
    #   - flame.icon=math-log # https://materialdesignicons.com/
    networks:
      default:
        ipv4_address: ${LOGSPOUT_IP}
networks:
  default:
    external: true
    name: main-network
# GET /logs
# GET /logs/id:<container-id>
# GET /logs/name:<container-name-pattern>
