# https://hub.docker.com/r/gliderlabs/logspout/
---
version: "3"
services:
  logspout:
    container_name: logspout
    image: gliderlabs/logspout:latest
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - ALLOW_TTY=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3902:80
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=logspout
      - flame.url=http://${HOSTNAME}:3902/logs # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=math-log # https://materialdesignicons.com/
      # - homepage.group=Monitoring and Analytics # homepage label https://github.com/benphelps/homepage
      # - homepage.name=logspout
      # - homepage.icon=mdi-math-log # https://gethomepage.dev/en/configs/services/#icons
      # - homepage.href=http://${HOSTNAME}:3902/logs
      # - homepage.description=
networks:
  default:
    external: true
    name: main-network
# GET /logs
# GET /logs/id:<container-id>
# GET /logs/name:<container-name-pattern>
