# https://docs.linuxserver.io/images/docker-lychee
---
version: "3"
services:
  lychee:
    container_name: lychee
    image: lscr.io/linuxserver/lychee:latest
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=lychee
      - DB_PASSWORD=${PASS}
      - DB_DATABASE=lychee
      - DB_PORT=3306
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/lychee/config:/config
      - ${DISK0}/pictures:/pictures
    ports:
      - 6791:80
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=lychee
      - flame.url=http://${HOSTNAME}:6791/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=image # https://materialdesignicons.com/
      - homepage.group=Media Servers/Streaming # homepage label https://github.com/benphelps/homepage
      - homepage.name=lychee
      - homepage.icon=lychee.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:6791/
      - homepage.description=
      # - homepage.widget.type=homepage
      # - homepage.widget.url=http://${HOST}:80/
      # - homepage.widget.key=yourembyapikeyhere
      # - homepage.widget.fields=["field1","field2"] # optional
networks:
  default:
    external: true
    name: main-network
