# https://hub.docker.com/r/linuxserver/mariadb
# https://hub.docker.com/_/mariadb/
---
version: "3"
services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      - TZ=Asia/Kuala_Lumpur
      - MARIADB_USER=mariadb
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped
    ports:
      - 3306:3306
networks:
  default:
    external: true
    name: main-network
volumes:
  mysqldata:
    external: true
