# https://github.com/usememos/memos
---
version: "3.2"
services:
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    ports:
      - "5230:5230"
    volumes:
      - /opt/memos:/var/opt/memos
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=memos
      - flame.url=http://${HOSTNAME}:5230/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=format-list-checks # https://materialdesignicons.com/
      - homepage.group=Knowledge/Content Management Systems # homepage label https://github.com/benphelps/homepage
      - homepage.name=memos
      - homepage.icon=memos.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:5230/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
