# https://github.com/alexta69/metube
---
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - ${DISK0}/downloads/metube:/downloads
    ports:
      - 8081:8081
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=metube
      - flame.url=https://metube.${DOMAIN}/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=youtube # https://materialdesignicons.com/
networks:
  default:
    external: true
    name: main-network
