# https://github.com/midarrlabs/midarr-server
---
services:
  midarr:
    container_name: midarr
    image: ghcr.io/midarrlabs/midarr-server:latest
    ports:
      - 4000:4000
    volumes:
      # - /opt/midarr/database:/app/database
      - /mnt/disk1/movies:/movies
      - /mnt/disk0/tvseries:/tv
    environment:
      - TZ=Asia/Kuala_Lumpur
      #       App config
      - APP_URL=http://torqueserver.home:4000
      # - APP_MAILER_FROM=

      #       Database config
      - DB_USERNAME=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DATABASE=midarr
      - DB_HOSTNAME=postgres

      #       Initialise admin account
      - SETUP_ADMIN_EMAIL=admin@torqueserver.com
      - SETUP_ADMIN_NAME=admin
      - SETUP_ADMIN_PASSWORD=${LONG_PASS} # minimum length 12

      #       Radarr integration
      - RADARR_BASE_URL=http://radarr:7878
      - RADARR_API_KEY=${RADARR_API_KEY}

      #       Sonarr integration
      - SONARR_BASE_URL=http://sonarr:8989/
      - SONARR_API_KEY=${SONARR_API_KEY}

    #       Sendgrid email integration
    # - SENDGRID_API_KEY=someApiKey

    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=midarr
      - flame.url=https://midarr.torqueserver.com/
      - flame.icon=play
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - main-network
networks:
  main-network:
    external: true
