# https://hub.docker.com/r/linuxserver/netbox
---
version: "2.1"
services:
  netbox:
    image: ghcr.io/linuxserver/netbox
    container_name: netbox
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - SUPERUSER_EMAIL=${EMAIL}
      - SUPERUSER_PASSWORD=${PASS}
      - ALLOWED_HOST=['*']
      - DB_NAME=netbox
      - DB_USER=root
      - DB_PASSWORD=${DB_PASS}
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # - REDIS_PASSWORD=<REDIS_PASSWORD>
      # - REDIS_DB_TASK=<REDIS_DB_TASK>
      # - REDIS_DB_CACHE=<REDIS_DB_CACHE>
      # - BASE_PATH=<BASE_PATH> #optional
      # - REMOTE_AUTH_ENABLED=<REMOTE_AUTH_ENABLED> #optional
      # - REMOTE_AUTH_BACKEND=<REMOTE_AUTH_BACKEND> #optional
      # - REMOTE_AUTH_HEADER=<REMOTE_AUTH_HEADER> #optional
      # - REMOTE_AUTH_AUTO_CREATE_USER=<REMOTE_AUTH_AUTO_CREATE_USER> #optional
      # - REMOTE_AUTH_DEFAULT_GROUPS=<REMOTE_AUTH_DEFAULT_GROUPS> #optional
      # - REMOTE_AUTH_DEFAULT_PERMISSIONS=<REMOTE_AUTH_DEFAULT_PERMISSIONS> #optional
    volumes:
      - /opt/netbox/config:/config
    ports:
      - 8305:8000
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
