# https://github.com/NginxProxyManager/nginx-proxy-manager
---

version: '3'
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /opt/nginx-proxy-manager/nginx:/data
      - /opt/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    labels:
      - flame.type=app # "app" works too
      - flame.name=nginx-proxy-manager
      - flame.url=http://torqueserver.home:81/
      - flame.icon=arrow-decision
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main-network
