# https://github.com/NginxProxyManager/nginx-proxy-manager
---
version: "3"
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - /opt/nginx-proxy-manager/nginx:/data
      - /opt/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=nginx-proxy-manager
      - flame.url=http://${HOSTNAME}:81/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=arrow-decision # https://materialdesignicons.com/
      - homepage.group=Web Servers # homepage label https://github.com/benphelps/homepage
      - homepage.name=nginx-proxy-manager
      - homepage.icon=nginx-proxy-manager.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:81/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
