# https://hub.docker.com/_/nginx
# https://hub.docker.com/r/linuxserver/nginx/#!
---
version: "2.1"
services:
  nginx:
    image: nginx
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/nginx/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
