# https://hub.docker.com/r/linuxserver/ngircd
# https://hub.docker.com/r/linuxserver/znc
# https://hub.docker.com/r/thelounge/thelounge
---
version: "3"
services:
  ngircd:
    container_name: ngircd
    image: lscr.io/linuxserver/ngircd:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/ngircd/config:/config
    ports:
      - 6667:6667
    restart: unless-stopped
    networks:
      - main-network
  znc:
    container_name: znc
    image: lscr.io/linuxserver/znc:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/znc/config:/config
    ports:
      - 6501:6501
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=znc
      - flame.url=http://torqueserver.home:6501/
      - flame.icon=transit-connection-variant
    networks:
      - main-network
  thelounge:
    container_name: thelounge
    image: thelounge/thelounge:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/thelounge:/var/opt/thelounge
    ports:
      - 9099:9000
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=thelounge
      - flame.url=https://thelounge.torqueserver.com/
      - flame.icon=chat-processing
    networks:
      - main-network
networks:
  main-network:
    external: true
