# https://github.com/thijsvanloef/palworld-server-docker
services:
  palworld-server:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      stop_grace_period: 30s # Set to however long you are willing to wait for the container to gracefully stop
      ports:
        - 8211:8211/udp
        # - 27015:27015/udp
        - 25575:25575
        # - 8212:8212/tcp  # Port for REST API if REST_API_ENABLED: true
      environment:
        PUID: 1000
        PGID: 1000
        PLAYERS: 16 # Optional but recommended
        PORT: 8211 # Optional but recommended
        # SERVER_PASSWORD: "123?palword" # Optional but recommended
        MULTITHREADING: true
        RCON_ENABLED: true
        RCON_PORT: 25575
        TZ: "Asia/Kuala_Lumpur"
        ADMIN_PASSWORD: "${PASS}"
        COMMUNITY: true  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
        SERVER_NAME: "Torqueserver Palword Server"
        SERVER_DESCRIPTION: "Credit to palworld-server-docker by Thijs van Loef"
        ALLOW_CONNECT_PLATFORM: "Steam" # Defaults to "Steam" if not set, set this to "Xbox" if you want to host a server for Xbox players. CROSSPLAY BETWEEN XBOX-STEAM IS NOT YET SUPPORTED
      volumes:
        - /opt/palworld:/palworld/
networks:
  default:
    external: true
    name: main-network