# https://hub.docker.com/r/linuxserver/papermerge
---
version: "2.1"
services:
  papermerge:
    image: lscr.io/linuxserver/papermerge:latest
    container_name: papermerge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - REDIS_URL=redis:6379 #optional
    volumes:
      - /opt/papermerge/config:/config
      - /opt/papermerge/data:/data
    ports:
      - 8230:8000
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=papermerge
      - flame.url=http://torqueserver.home:8230/
      - flame.icon=file
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main_network
