# https://hub.docker.com/r/dpage/pgadmin4
---
version: "2.3"
services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    hostname: pgadmin4
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PASS}
    ports:
      - 8889:80
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=pgadmin4
      - flame.url=http://${HOSTNAME}:8889/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=database # https://materialdesignicons.com/
      - homepage.group=Database Management Systems # homepage label https://github.com/benphelps/homepage
      - homepage.name=pgadmin4
      - homepage.icon=pgadmin4.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:8889/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
