# https://hub.docker.com/r/linuxserver/plex
---
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      # - PLEX_CLAIM= ${PLEX_CLAIM}
    volumes:
      - /opt/plex/config:/config
      - /home/yuu/media/tv:/tv
      - /home/yuu/media/movies:/movies
      - /home/yuu/media/music:/music
      - /dev/dri:/dev/dri
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=plex
      - flame.url=plex.torqueserver.com/
      # - flame.url=http://192.168.0.126:32400/web/index.html
      - flame.icon=plex
