# https://hub.docker.com/r/linuxserver/plex
---
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    hostname: plex
    network_mode: host
    # runtime: nvidia # Expose NVIDIA GPUs
    # environment:
    #   - PLEX_CLAIM= ${PLEX_CLAIM}
    volumes:
      - /opt/plex/config:/config
      - ${DISK0}/tvseries:/tvseries
      - ${DISK0}/movies:/movies
      - /dev/dri:/dev/dri
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=plex
      - flame.url=https://plex.${DOMAIN}/web/ 
      - flame.icon=plex
