---
version: "2.1"
services:
  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager
    container_name: plex-meta-manager
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - PMM_CONFIG=/config/config.yml #optional
      - PMM_TIME=03:00 #optional
      - PMM_RUN=False #optional
      - PMM_TEST=False #optional
      - PMM_NO_MISSING=False #optional
    volumes:
      - /opt/plex-meta-manager/config:/config
    restart: unless-stopped
networks:
  default:
    external: true
    name: main-network