# https://hub.docker.com/_/postgres/
# https://hub.docker.com/r/dpage/pgadmin4
---
services:
  postgres:
    container_name: postgres
    image: postgres:17.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg-data:/var/lib/postgresql/data/
      # - /opt/postgres/postgres.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: elestio/pgadmin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8008:80"
    depends_on:
      - "postgres"
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=pgadmin
      - flame.url=http://${LOCAL_HOSTNAME}:8008/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=database # https://materialdesignicons.com/
    restart: unless-stopped
networks:
  default:
    external: true
    name: main-network
volumes:
  pg-data:
    external: true
