# https://prometheus.io/docs/prometheus/latest/installation/
# https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus.yml
--- 
version: "3"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    ports:
      - 9090:9090
    volumes:
      - /opt/prometheus:/etc/prometheus
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=prometheus
      - flame.url=http://torqueserver.home:9090/
      - flame.icon=finance
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main_network
