# https://prometheus.io/docs/prometheus/latest/installation/
# https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus.yml
---
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - /opt/prometheus:/etc/prometheus
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=prometheus
      - flame.url=http://${HOSTNAME}:9090/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=finance # https://materialdesignicons.com/
networks:
  default:
    external: true
    name: main-network
