# https://hub.docker.com/r/linuxserver/prowlarr
---
version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=prowlarr
      - flame.url=http://${HOSTNAME}:9696/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=target # https://materialdesignicons.com/
      # - homepage.group=Indexing & Search # homepage label https://github.com/benphelps/homepage
      # - homepage.name=prowlarr
      # - homepage.icon=prowlarr.png # https://gethomepage.dev/en/configs/services/#icons
      # - homepage.href=http://${HOSTNAME}:9696/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      # - homepage.description=
networks:
  default:
    external: true
    name: main-network
