# https://hub.docker.com/r/linuxserver/radarr
---
version: "2.1"
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/radarr/config:/config
      - /mnt/disk1/movies:/movies
      - /mnt/disk0/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=radarr
      - flame.url=http://192.168.0.105:7878/
      - flame.icon=radar
networks:
  default:
    external: true
    name: main-network
