# https://hub.docker.com/r/linuxserver/readarr
---
version: "2.1"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/readarr/config:/config
      - ${DISK0}/books:/books #optional
      - ${DISK0}/downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=readarr
      - flame.url=http://${HOSTNAME}:8787/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=book # https://materialdesignicons.com/
      - homepage.group= # homepage label https://github.com/benphelps/homepage
      - homepage.name=readarr
      - homepage.icon=readarr.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:808787/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
