# https://docs.redis.com/latest/ri/installing/install-docker/
# https://hub.docker.com/_/redis/
---
version: "3.2"
services:
  redis:
    image: "redis:7-alpine"
    command: redis-server # --requirepass ${REDIS_PASSWORD}
    container_name: redis
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - redisdata:/data
      # - /opt/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
  redisinsight:
    image: "redislabs/redisinsight:latest"
    container_name: redisinsight
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - redisinsight:/db
    ports:
      - 8002:8001
    depends_on:
      - "redis"
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=redisinsight
      - flame.url=http://${HOSTNAME}:8002/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=database # https://materialdesignicons.com/
      - homepage.group=Database # homepage label https://github.com/benphelps/homepage
      - homepage.name=redisinsight
      - homepage.icon=redis.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:8002/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
volumes:
  redisdata:
    external: true
  redisinsight:
    external: true
