# https://docs.redis.com/latest/ri/installing/install-docker/
# https://hub.docker.com/_/redis/
---
services:
  redis:
    image: "redis:7.0"
    command: redis-server # --requirepass ${REDIS_PASSWORD}
    container_name: redis
    volumes:
      - redisdata:/data
      # - /opt/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    ports:
      - 6379:6379
    labels:
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main-network
volumes:
  redisdata:
    external: true
