# https://hub.docker.com/r/inglebard/retroarch-web
---
version: "3"
services:
  retroarch:
    image: inglebard/retroarch-web
    container_name: retroarch
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    ports:
      - "9808:80"
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=retroarch
      - flame.url=http://torqueserver.home:9808/
      - flame.icon=gamepad
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main-network
