# https://hub.docker.com/r/inglebard/retroarch-web
---
version: "3"
services:
  retroarch:
    image: inglebard/retroarch-web
    container_name: retroarch
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    ports:
      - "9808:80"
    restart: unless-stopped
  labels:
    - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
    - flame.type=app # flame label https://github.com/pawelmalak/flame
    - flame.name=retroarch
    - flame.url=http://${HOSTNAME}:9808/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
    - flame.icon=gamepad # https://materialdesignicons.com/
    - homepage.group=Games # homepage label https://github.com/benphelps/homepage
    - homepage.name=retroarch
    - homepage.icon=mdi-gamepad # https://gethomepage.dev/en/configs/services/#icons
    - homepage.href=http://${HOSTNAME}:9808/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
    - homepage.description=
networks:
  default:
    external: true
    name: main-network
