# https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/docker/
---
services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - /opt/rustdesk/data:/root
    network_mode: "host"
    depends_on:
      - hbbr
    restart: unless-stopped
  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - /opt/rustdesk/data:/root
    network_mode: "host"
    restart: unless-stopped
