# https://hub.docker.com/r/linuxserver/snipe-it
---
services:
  snipe-it:
    image: lscr.io/linuxserver/snipe-it:latest
    container_name: snipe-it
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - APP_URL=http://snipeit.${DOMAIN}
      - MYSQL_PORT_3306_TCP_ADDR=mariadb
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=${PASS}
    volumes:
      - /opt/snipeit/config:/config
    # ports:
      # - 8085:80
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=snipe-it
      - flame.url=https://snipeit.${DOMAIN}/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=desktop-classic # https://materialdesignicons.com/
networks:
  default:
    external: true
    name: main-network
