# https://hub.docker.com/r/linuxserver/tautulli
# https://hub.docker.com/r/tautulli/tautulli
---
services:
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /opt/tautulli/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    ports:
      - 8181:8181
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=tautulli
      - flame.url=http://${HOSTNAME}:8181/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=chart-timeline # https://materialdesignicons.com/
networks:
  default:
    external: true
    name: main-network
