# https://hub.docker.com/r/linuxserver/thelounge
---
services:
  thelounge:
    container_name: thelounge
    image: thelounge/thelounge:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/thelounge:/var/opt/thelounge
    # ports:
      # - 9099:9000
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=thelounge
      - flame.url=https://thelounge.${DOMAIN}/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=chat-processing # https://materialdesignicons.com/
networks:
  default:
    external: true
    name: main-network
