# https://hub.docker.com/r/linuxserver/thelounge
---
version: "2.1"
services:
  thelounge:
    image: lscr.io/linuxserver/thelounge:latest
    container_name: thelounge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/thelounge/config:/config
    ports:
      - 9009:9000
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=thelounge
      - flame.url=http://torqueserver.home:9009/
      - flame.icon=chat
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main_network
