# https://umami.is/docs/install
---
version: "3"
services:
  umami:
    container_name: umami
    image: ghcr.io/umami-software/umami:postgresql-latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${XPASS}@postgres:5432/umami
      - DATABASE_TYPE=postgresql
      - HASH_SALT=replace-me-with-a-random-string
    ports:
      - "3100:3000"
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=umami
      - flame.url=https://umami.${DOMAIN}/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=finance # https://materialdesignicons.com/
      - homepage.group=Monitoring and Analytics # homepage label https://github.com/benphelps/homepage
      - homepage.name=umami
      - homepage.icon=umami.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=https://umami.${DOMAIN}/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
