# https://hub.docker.com/r/linuxserver/wikijs
---
services:
  wikijs:
    image: ghcr.io/requarks/wiki:2
    container_name: wikijs
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: ${PASS}
      DB_NAME: wikijs
    # ports:
      # - "80:3000"
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=wikijs
      - flame.url=https://wikijs.${DOMAIN}/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=book-open-variant # https://materialdesignicons.com/
networks:
  default:
    external: true
    name: main-network
