# https://hub.docker.com/_/wordpress/
---
version: "3.1"
services:
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    environment:
      TZ: Asia/Kuala_Lumpur
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=wordpress
      - flame.url=https://wp.${DOMAIN}/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=wordpress # https://materialdesignicons.com/
      - homepage.group=Knowledge/Content Management Systems # homepage label https://github.com/benphelps/homepage
      - homepage.name=wordpress
      - homepage.icon=wordpress.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=https://wp.${HOSTNAME}/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
volumes:
  wordpress:
    external: true
