# https://github.com/fmartinou/whats-up-docker
---
version: "3"
services:
  whatsupdocker:
    container_name: whatsupdocker
    image: fmartinou/whats-up-docker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3201:3000
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=whatsupdocker
      - flame.url=http://${HOSTNAME}:3201/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=docker # https://materialdesignicons.com/
      - homepage.group=Container Management # homepage label https://github.com/benphelps/homepage
      - homepage.name=whatsupdocker
      - homepage.icon=docker.png # https://gethomepage.dev/en/configs/services/#icons
      - homepage.href=http://${HOSTNAME}:3201/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - homepage.description=
networks:
  default:
    external: true
    name: main-network
