# https://hub.docker.com/r/linuxserver/znc
---
version: "2.1"
services:
  znc:
    image: lscr.io/linuxserver/znc:latest
    container_name: znc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/znc/config:/config
    ports:
      - 6501:6501
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=znc
      - flame.url=http://torqueserver.home:6501/
      - flame.icon=chat-processing
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main_network
