# https://hub.docker.com/r/linuxserver/znc
---
version: "2.1"
services:
  znc:
    container_name: znc
    image: lscr.io/linuxserver/znc:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/znc/config:/config
    ports:
      - 6501:6501
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=znc
      - flame.url=http://${HOSTNAME}:6501/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=transit-connection-variant # https://materialdesignicons.com/
      # - homepage.group=IRC Servers and Clients # homepage label https://github.com/benphelps/homepage
      # - homepage.name=znc
      # - homepage.icon=znc.png # https://gethomepage.dev/en/configs/services/#icons
      # - homepage.href=http://${HOSTNAME}:6501/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      # - homepage.description=
networks:
  default:
    external: true
    name: main-network
