# https://github.com/pawelmalak/flame
---
version: "3.6"

services:
  flame:
    image: pawelmalak/flame
    volumes:
      - flame_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    ports:
      - 5005:5005
    secrets:
      - password
    environment:
      - PASSWORD_FILE=/run/secrets/password # optional but required for (1)
    networks:
      - overlay_network

networks:
  overlay_network:
    external: true

volumes:
  flame_data:
    external: true

secrets:
  password:
    file: ./password.txt
# secrets: # not working, check issues in github
#   password: # not working, check issues in github
#     external: true # not working, check issues in github
