# https://github.com/linuxserver/docker-swag
# https://docs.linuxserver.io/general/swag
# https://www.smarthomebeginner.com/docker-authelia-tutorial/
---
version: "2.1"
services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    ports:
      - 9091:9091
    volumes:
      - /opt/authelia/config:/config
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=authelia
      - flame.url=https://authelia.torqueserver.com/
      - flame.icon=two-factor-authentication
      - com.centurylinklabs.watchtower.enable=true
      # traefik
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.authelia-rtr.entrypoints=https"
      - "traefik.http.routers.authelia-rtr.rule=Host(`authelia.$DOMAINNAME_CLOUD_SERVER`)"
      - 'traefik.http.routers.authelia.tls=true'
      ## Middlewares
      - "traefik.http.routers.authelia-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.authelia-rtr.service=authelia-svc"
      - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"
networks:
  default:
    external: true
    name: main_network
