---
version: "3.3"
services:
  axigen:
    image: axigen/axigen
    container_name: axigen
    volumes:
      - '/opt/axigen:/var/opt/axigen'
    ports:
      - '2443:443'
      - '9343:9443'
      - '993:993'
      - '995:995'
      - '225:25'
      - '465:465'
      - '9009:9000'
      - '7000:7000'
    restart: unless-stopped
networks:
  default:
    external: true
    name: main-network