# https://hub.docker.com/r/linuxserver/bookstack
---
version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://torqueserver.home:6875/
      - DB_HOST=mariadb
      - DB_USER=bookstack
      - DB_PASS=${DB_PASS}
      - DB_DATABASE=bookstack
    volumes:
      - /opt/bookstack/config:/config
    ports:
      - 6875:80
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=bookstack
      - flame.url=http://torqueserver.home:6875/
      - flame.icon=book-open
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main_network
