# https://github.com/prometheus-net/docker_exporter
---
version: "2.1"
services:
  docker-exporter:
    image: prometheusnet/docker_exporter
    container_name: docker-exporter
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9417:9417
    restart: always
networks:
  default:
    external: true
    name: main
