# https://hub.docker.com/r/diouxx/glpi
---
version: '3'
services:
  glpi:
    image: diouxx/glpi
    container_name: glpi
    ports:
      - '8324:80'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=glpi
      - flame.url=http://torqueserver.home:8324/
      - flame.icon=ticket
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main_network
