# https://hub.docker.com/r/linuxserver/hedgedoc
---
version: "3"
services:
  hedgedoc:
    image: lscr.io/linuxserver/hedgedoc:latest
    container_name: hedgedoc
    restart: always
    volumes:
      - /opt/hedgedoc/config:/config
    environment:
      - DB_HOST=mariadb
      - DB_USER=hedgedoc
      - DB_PASS=${PASS}
      - DB_NAME=hedgedoc
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Kuala_Lumpur
      - CMD_DOMAIN=localhost
      - CMD_URL_ADDPORT=true #optional
      - CMD_PROTOCOL_USESSL=false #optional
      - CMD_PORT=3000 #optional
    ports:
      - "3033:3000"
    labels:
      - flame.type=app # "app" works too
      - flame.name=hedgedoc
      - flame.url=https://hedgedoc.torqueserver.com/
      - flame.icon=language-markdown
      - com.centurylinklabs.watchtower.enable=true
      # traefik
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.hedgedoc-rtr.entrypoints=https"
      - "traefik.http.routers.hedgedoc-rtr.rule=Host(`hedgedoc.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.hedgedoc-rtr.tls=true"
      ## Middlewares
      # - "traefik.http.routers.heimdall-rtr.middlewares=chain-basic-auth@file"
      - "traefik.http.routers.hedgedoc-rtr.middlewares=chain-no-auth@file"
      # - "traefik.http.routers.heimdall-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.hedgedoc-rtr.service=hedgedoc-svc"
      - "traefik.http.services.hedgedoc-svc.loadbalancer.server.port=3000"
networks:
  default:
    external: true
    name: main_network
