# https://fleet.linuxserver.io/image?name=linuxserver/heimdall
---
version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/heimdall/config:/config
    ports:
      - 8888:80
      - 3443:443
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=heimdall
      - flame.url=https://h.torqueserver.com/
      - flame.icon=crown
      - com.centurylinklabs.watchtower.enable=true
      # traefik
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.heimdall-rtr.entrypoints=https"
      - "traefik.http.routers.heimdall-rtr.rule=Host(`h.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.heimdall-rtr.tls=true"
      ## Middlewares
      # - "traefik.http.routers.heimdall-rtr.middlewares=chain-basic-auth@file"
      # - "traefik.http.routers.heimdall-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.heimdall-rtr.service=heimdall-svc"
      - "traefik.http.services.heimdall-svc.loadbalancer.server.port=80"
networks:
  default:
    external: true
    name: main_network
