# https://hub.docker.com/r/linuxserver/htpcmanager
---
version: "2.1"
services:
  htpcmanager:
    image: ghcr.io/linuxserver/htpcmanager
    container_name: htpcmanager
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/htpcmanager/config:/config
    ports:
      - 8085:8085
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
