# https://hub.docker.com/r/linuxserver/mariadb
# https://hub.docker.com/_/mariadb/
# ---
# version: "2.1"
# services:
#   mariadb:
#     image: ghcr.io/linuxserver/mariadb
#     container_name: mariadb
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#       - TZ=Asia/Kuala_Lumpur
#       - MYSQL_DATABASE=mariadb #optional
#       - MYSQL_USER=mariadb #optional
#       - MYSQL_PASSWORD=${MYSQL_PASSWORD} #optional
#       #- REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
#     volumes:
#       - /opt/mariadb/config:/config
#     ports:
#       - 3306:3306
#     restart: unless-stopped
# networks:
#   default:
#     external: true
#     name: main-network
---
version: "3"
services:
  mariadb:
    image: mariadb:10.9.2
    container_name: mariadb
    environment:
      - TZ=Asia/Kuala_Lumpur
      - MARIADB_USER=mariadb
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      # - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      # - PMA_USER=root
      # - PMA_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      # - /opt/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - /opt/phpmyadmin/themes:/www/themes/
      - phpmyadminsessions:/sessions/
    ports:
      - 8880:80
    labels:
      - flame.type=app # "app" works too
      - flame.name=phpmyadmin
      - flame.url=http://torqueserver.home:8880/
      - flame.icon=database
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
networks:
  default:
    external: true
    name: main-network
volumes:
  phpmyadminsessions:
    external: true
  mysqldata:
    external: true
