# https://hub.docker.com/_/mediawiki
---
version: "3"
services:
  mediawiki:
    image: mediawiki
    container_name: mediawiki
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    # ports:
    #   - 5080:80
    volumes:
      - /var/www/html/images
      #- /opt/mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php # comment this for firsttime setup, then after finish setup, uncomment this
      # After initial setup, download LocalSettings.php to the same directory as
      # this yaml and uncomment the following line and use compose to restart
      # the mediawiki service
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php
    labels:
      - flame.type=app # "app" works too
      - flame.name=mediawiki
      - flame.url=https://wiki.torqueserver.com/
      - flame.icon=wiki
networks:
  default:
    external: true
    name: main-network
