# https://github.com/alexta69/metube
version: "3"
services:
  metube:
    image: alexta69/metube
    container_name: metube
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /mnt/disk0/downloads:/downloads
    ports:
      - 8081:8081
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=metube
      - flame.url=http://torqueserver.home:8081/
      - flame.icon=youtube
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main-network
