# https://miniflux.app/docs/installation.html#docker
---
version: '3.4'
services:
  miniflux:
    image: miniflux/miniflux:latest
    container_name: miniflux
    ports:
      - "8764:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      # - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=miniflux
      - flame.url=http://torqueserver.home:8764/
      - flame.icon=rss-box
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main_network