# https://hub.docker.com/r/linuxserver/papermerge
---
version: "2.1"
services:
  papermerge:
    image: ghcr.io/linuxserver/papermerge
    container_name: papermerge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - REDIS_URL=redis:6379 #optional
    volumes:
      - /opt/papermerge/config:/config
      - /opt/papermerge/data:/data
    ports:
      - 8230:8000
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
