# https://hub.docker.com/r/linuxserver/phpmyadmin
---
version: "2.1"
services:
  phpmyadmin:
    image: ghcr.io/linuxserver/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - PMA_ARBITRARY=1 #optional
      #- PMA_ABSOLUTE_URI=http://192.168.0.105:8808/ #optional
    volumes:
      - /opt/phpmyadmin/config:/config
    ports:
      - 8808:80
    restart: unless-stopped
networks:
  default:
    external: true
    name: main
