#https://github.com/pi-hole/docker-pi-hole
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp" # to disable dnsamq for ubuntu run the following; `sudo systemctl stop systemd-resolved`; `sudo systemctl disable systemd-resolved`
      - "67:67/udp"
      - "8087:80/tcp"
    environment:
      TZ: "Asia/Kuala_Lumpur"
      # WEBPASSWORD: ${PASS}
    # Volumes store your data between container upgrades
    volumes:
      - "/opt/pihole/etc/pihole/:/etc/pihole/"
      - "/opt/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/"
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=pihole
      - flame.url=http://torqueserver.home:8087/admin/
      - flame.icon=pi-hole
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main_network
