# https://hub.docker.com/r/linuxserver/plex
---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      # - PLEX_CLAIM= ${PLEX_CLAIM}
    # ports:
    #   - "32400:32400/tcp"
    #   - "3005:3005/tcp"
    #   - "8324:8324/tcp"
    #   - "32469:32469/tcp"
    #   - "1900:1900/udp"
    #   - "32410:32410/udp"
    #   - "32412:32412/udp"
    #   - "32413:32413/udp"
    #   - "32414:32414/udp"
    volumes:
      - /opt/plex/config:/config
      - /mnt/disk0/tvseries:/tv
      - /mnt/disk1/movies:/movies
      - /dev/dri:/dev/dri
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=plex
      - flame.url=http://torqueserver.home:32400/
      - flame.icon=plex
      - com.centurylinklabs.watchtower.enable=true
      # traefik
      # - "traefik.enable=true"
      ## HTTP Routers
      # - "traefik.http.routers.plex-rtr.entrypoints=https"
      # - "traefik.http.routers.plex-rtr.rule=Host(`plex.$DOMAINNAME_CLOUD_SERVER`)"
      # - "traefik.http.routers.plex-rtr.tls=true"
      ## Middlewares
      # - "traefik.http.routers.jellyfin-rtr.middlewares=chain-basic-auth@file"
      # - "traefik.http.routers.plex-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      # - "traefik.http.routers.plex-rtr.service=plex-svc"
      # - "traefik.http.services.plex-svc.loadbalancer.server.port=32400"
# networks:
#   default:
#     external: true
#     name: main-network