# https://example.com/
---
version: "3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "8000:8000"
      - "9000:9000"
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=portainer
      - flame.url=http://torqueserver.home:9000/
      - flame.icon=image-multiple
    networks:
      - main-network
networks:
  main-network:
    external: true
volumes:
  portainer_data:
    external: true
