# https://hub.docker.com/r/linuxserver/prowlarr
---
version: "2.1"
services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:nightly-alpine
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=prowlarr
      - flame.url=http://192.168.0.105:9696/
      - flame.icon=target
networks:
  default:
    external: true
    name: main-network
