# https://hub.docker.com/r/linuxserver/qbittorrent
---
version: "2.1"
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - WEBUI_PORT=8080
    volumes:
      - /opt/qbittorrent/config:/config
      - /mnt/disk0/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
    labels:
      # - flame.type=app # "app" works too
      # - flame.name=qbittorrent
      # - flame.url=http://192.168.0.126:8080/
      # - flame.icon=download
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main_network
