# https://docs.redis.com/latest/ri/installing/install-docker/
# https://hub.docker.com/_/redis/
---
version: "3.2"
services:
  redis:
    image: "redis:7.0.0-alpine"
    command: redis-server # --requirepass ${REDIS_PASSWORD}
    container_name: redis
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - redisdata:/data
      # - /opt/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
  redisinsight:
    image: "redislabs/redisinsight:latest"
    container_name: redisinsight
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - redisinsight:/db
    ports:
      - 8002:8001
    depends_on:
      - "redis"
    labels:
      - flame.type=app # "app" works too
      - flame.name=redisinsight
      - flame.url=http://torqueserver.home:8002/
      - flame.icon=database
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
networks:
  default:
    external: true
    name: main_network
volumes:
  redisdata:
    external: true
  redisinsight:
    external: true