# https://shlink.io/documentation/install-docker-image/
# https://github.com/shlinkio/shlink-web-client
---
version: '3'
services:
  shlink:
    container_name: shlink
    image: 'shlinkio/shlink:stable'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - DEFAULT_DOMAIN=trqs.xyz
      - IS_HTTPS_ENABLED=true
      - GEOLITE_LICENSE_KEY=${GEOLITE_LICENSE_KEY}
      - DB_DRIVER=mysql
      - DB_USER=shlink
      - DB_PASSWORD=${DB_PASS}
      - DB_HOST=mariadb:3306
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
      # traefik
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.shlink-rtr.entrypoints=https"
      - "traefik.http.routers.shlink-rtr.rule=Host(`$DOMAINNAME2`)"
      - "traefik.http.routers.shlink-rtr.tls=true"
      ## Middlewares
      # - "traefik.http.routers.jellyfin-rtr.middlewares=chain-basic-auth@file"
      - "traefik.http.routers.shlink-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.shlink-rtr.service=shlink-svc"
      - "traefik.http.services.shlink-svc.loadbalancer.server.port=8080"
  shlink-web-client:
    container_name: shlink-web-client
    image: shlinkio/shlink-web-client
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - SHLINK_SERVER_URL=https://trqs.xyz
      - SHLINK_SERVER_API_KEY=${SHLINK_SERVER_API_KEY}
    ports:
      - '8020:80'
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=shlink-web-client
      - flame.url=http://torqueserver.home:8020/
      - flame.icon=text-short
networks:
  default:
    external: true
    name: main_network