# https://hub.docker.com/r/linuxserver/snipe-it
---
version: "2.1"
services:
  snipe-it:
    image: lscr.io/linuxserver/snipe-it:latest
    container_name: snipe-it
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://torqueserver.home:8085
      - MYSQL_PORT_3306_TCP_ADDR=mariadb
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/snipeit/config:/config
    ports:
      - 8085:80
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=snipe-it
      - flame.url=http://torqueserver.home:8085
      - flame.icon=desktop-classic
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    external: true
    name: main_network