#https://github.com/linuxserver/docker-syncthing
---
version: "2.1"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/syncthing/config:/config
      - /mnt/disk0:/data0
      - /mnt/disk1:/data1
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=syncthing
      - flame.url=https://sync.torqueserver.com/
      - flame.icon=file-sync
      - com.centurylinklabs.watchtower.enable=true
      # traefik
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.syncthing-rtr.entrypoints=https"
      - "traefik.http.routers.syncthing-rtr.rule=Host(`sync.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.syncthing-rtr.tls=true"
      ## Middlewares
      # - "traefik.http.routers.syncthing-rtr.middlewares=chain-basic-auth@file"
      - "traefik.http.routers.syncthing-rtr.middlewares=chain-no-auth@file"
      # - "traefik.http.routers.syncthing-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.syncthing-rtr.service=syncthing-svc"
      - "traefik.http.services.syncthing-svc.loadbalancer.server.port=8384"
networks:
  default:
    external: true 
    name: main_network