# https://hub.docker.com/r/linuxserver/taisun
---
version: "2"
services:
  taisun:
    image: linuxserver/taisun
    container_name: taisun
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3330:3000
    restart: unless-stopped
