# https://hub.docker.com/r/linuxserver/wireshark
---
version: "2.1"
services:
  wireshark:
    image: ghcr.io/linuxserver/wireshark
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /opt/wireshark/config:/config
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=wireshark
      - flame.url=http://torqueserver.home:3000/
      - flame.icon=shark
      - com.centurylinklabs.watchtower.enable=true