# https://hub.docker.com/_/wordpress/
# https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-docker-compose
---
version: "3.1"
services:
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    environment:
      TZ: Asia/Kuala_Lumpur
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    labels:
      - flame.type=app # "app" works too
      - flame.name=torqueserver
      - flame.url=https://torqueserver.com/
      - flame.icon=server
networks:
  default:
    external: true
    name: main-network
volumes:
  wordpress:
    external: true
