# https://hub.docker.com/_/wordpress/
# https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-docker-compose
---
version: "3.1"
services:
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    environment:
      TZ: Asia/Kuala_Lumpur
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    labels: #wordpress+proxmox+custom
      - flame.type=app
      - flame.name=wordpress;torqueserver;proxmox;dir
      - flame.url=https://wp.torqueserver.com/;https://torqueserver.com/;https://proxmox.torqueserver.com/;https://dir.torqueserver.com/
      - flame.icon=wordpress;server-network;file-tree
networks:
  default:
    external: true
    name: main-network
volumes:
  wordpress:
    external: true
