# https://example.com/
---
version: "3"
services:
  whatsupdocker:
    container_name: whatsupdocker
    image: fmartinou/whats-up-docker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3000
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=whatsupdocker
      - flame.url=https://torqueserver.home:3001/
      - flame.icon=docker
networks:
  default:
    external: true
    name: main-network
